### ISSUE TITLE
annotation of genes needs to take strandness into account?

### ISSUE THREAD

**Issue by crazyhottommy** [cole-trapnell-lab/cicero-release#21]
Hi,

I am following https://cole-trapnell-lab.github.io/cicero-release/docs/#cicero-gene-activity-scores
and 

```r
# Make a subset of the gene annotation column containing just the coordinates and the 
# gene name
gene_annotation_sub <- gene_annotation_sample[,c(1:3, 8)]

# Rename the gene symbol column to "gene"
names(gene_annotation_sub)[4] <- "gene"
```
only the chr, start, end and gene information are used. should add the strandness information as well?  TSS (transcription start site) will be at the start if strand is +  and at the end if strand is -.

thanks!

**Comment by hpliner** [comment]
Calculating gene activity scores requires annotation of which sites are promoters (and which gene they are). The lines you quoted are one way of adding this annotation, but any way that follows the requirements (described on the website) would work. The function I used above to annotate looks for any overlap in the range given regardless of strand. When creating your own gene_annotation_sample object, you'll want to define it using whatever parameters you want for "promoter" could be 500bp around the TSS, upstream of the TSS, etc. So depending on where you got your gene annotation info from, you likely will need to modify it to be a promoter file rather than a gene file. Hope this helps, reopen if you have follow up qs.

**Comment by crazyhottommy** [comment]
thank you for your explanation. A side question, I see you mentioned: "We have found that often, accessibility at promoters is a poor predictor of gene expression". Where is the reference?

**Comment by hpliner** [comment]
Apologies for the delay. This statement refers to our own observations as
discussed in Cicero's accompanying paper
https://www.cell.com/molecular-cell/fulltext/S1097-2765(18)30547-1#%20.
Though I have heard similar reports from others, I don't have a specific
citation where this is thoroughly discussed.

**Comment by crazyhottommy** [comment]
Thanks for the reply.
