### ISSUE TITLE
Running cicero on bulk data 

### ISSUE THREAD

**Issue by amr15** [cole-trapnell-lab/cicero-release#32]
Hi, 

I had a naive question--if I'm trying to run cicero on bulk atac-seq data, should I assign each peak randomly to 100 cells?  What is the best way to convert cicero for bulk use? 

Best,
Anu

**Comment by hpliner** [comment]
Hi Anu,

Unfortunately Cicero is designed for use with single-cell data, and the algorithm will not work with bulk data. It's possible that you could use it with bulk if you have many many replicates (though I make no promises). Because of the correlation calculations, you won't be able to divide up bulk data in a way that will make Cicero work.

Sorry about that,
Hannah
