### ISSUE TITLE
how to compare two sample using plot_connections 

### ISSUE THREAD

**Issue by honghh2018** [cole-trapnell-lab/cicero-release#45]
Hi @ctrapnell and all
      I have two sample, treatment and control, and I want to compare specific position between treatment and control sample using plot_connections. Base above request, what should i do on 
this cases.
      I wonder what the line that plot_connections showed mean ? whether or not it showed the 
   connective weight on curl line?

**Comment by hpliner** [comment]
Thank you for using Cicero. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Cicero user group here: https://groups.google.com/forum/#!members/cicero-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Cicero developers

I recommend you look here https://cole-trapnell-lab.github.io/cicero-release/docs/#advanced-visualizaton for information about plotting two datasets for comparison
