### ISSUE TITLE
Aggregating Co-Accessible Peaks

### ISSUE THREAD

**Issue by yanwu2014** [cole-trapnell-lab/cicero-release#5]
Hey guys! I just had a quick question about aggregating peaks. Is there a reason the default peak aggregation is using nearby peaks instead of aggregating co-accessible peaks?

**Comment by hpliner** [comment]
Generally we're aggregating peaks only during clustering/pseudotime ordering, and usually that means we haven't calculated co-accessibility yet. Once we can, we've found it's generally better to aggregate cells to get into the count regime instead of peaks. Obviously depends on what you want to do with it!
