### ISSUE TITLE
Does cicero include negative correlations in co-accessibility?

### ISSUE THREAD

**Issue by decapicone** [cole-trapnell-lab/cicero-release#72]
Hi, I am just wondering if the cis co accessible networks contain peaks that are inversely correlated with the rest of the network.  I see some values in my conns dataframe (from `run_cicero`) are negative.  So this means that inversely related peaks are also included in the networks, right? 

Most of the documentation talks about co-accessibility which makes it seem like it only counts positive correlations.

Thanks, any insight appreciated!

**Comment by hpliner** [comment]
Hello, yes, negative correlations are also calculated, which as you said would be inversely correlated. We in general had a hard time interpreting and validating these connections which is why we don't spend much time on them in the paper or documentation. I have heard from others of instances showing up where it seems like perhaps two competing orientations are showing up as negative correlations... would certainly be interesting to explore. Hope this helps!

**Comment by danielcgingerich** [comment]
@hpliner do the negative values in conns dataframe mean the correlation is negative? 

Thanks

**Comment by hpliner** [comment]
@danielcgingerich Yes, they do.

**Comment by hpliner** [comment]
I'm going to close, reopen if you have further questions
